apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: git-bp
  project: giri
spec:
  base:
    name: minimal
    version: 3.2.0
  customAddons:
  - name: ui-addon
    version: v1
  - name: git1-addon
    version: v1
  defaultAddons:
    csiSecretStoreConfig:
      providers: {}
    enableIngress: true
    enableMonitoring: true
    enableVM: true
    monitoring:
      gpuOperator:
        enabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: draft
